version: "2"
services:
  mongors1:
    container_name: mongors1
    image: mongo:3.4.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    expose:
      - "27018"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors1:/data/db

  mongors2:
    container_name: mongors2
    image: mongo:3.4.4
    command: mongod --noprealloc --smallfiles --shardsvr --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth
    environment:
      TERM: xterm
    expose:
      - "27018"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongors2:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo:3.4.4
    command: mongod --noprealloc --smallfiles --replSet mongocfgrs --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
         - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIR}/mongocfg1:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.4.4
    depends_on:
      - mongors1
      - mongors2
      - mongocfg1
    command: mongos --configdb mongocfgrs/mongocfg1:27017 --port 27017
    expose:
      - "27017"
    ports:
      - "27020:27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
